### ISSUE TITLE
Keyframes not being saved

### ISSUE THREAD

**Issue by dsbrgg** [Adobe-CEP/Samples#95] opened 2018-11-17 23:32 UTC
I've been trying to update keyframes on a simple clip which is just an image.
I've basically followed [this implementation](https://github.com/Adobe-CEP/Samples/blob/master/PProPanel/jsx/PPRO/Premiere.jsx#L1315) which was the only good example I saw on playing around with keyframes.

It seems that my image is actually updated and after the script is run, it really does change the component property(`Scale` in this case) and leaves the final result there. The only problem is that the keyframes are not being saved from what I can tell even though logging the `component[].properties[].getKeys()` return an array of `Time` objects.

I don't know if this is actually a bug or if it's something that I've missed when reading through the script on github. Anyway, any help is appreciated!

**Comment by bbb999** [comment] 2018-11-19 15:43
Is keyframing enabled, for the streams you're modifying?

**Comment by dsbrgg** [comment] 2018-11-19 16:49
@bbb999 do you mean `.setTimeVarying()`? Which I suppose enables the toggle animation on Premiere.

**Comment by bbb999** [comment] 2018-11-19 16:51
Yep! 

isTimeVarying: http://ppro.aenhancers.com/9%20-%20Component%20Parameter%20object/componentparam.html?highlight=settimevary#istimevarying

setTimeVarying: http://ppro.aenhancers.com/9%20-%20Component%20Parameter%20object/componentparam.html?highlight=settimevary#settimevarying

**Comment by dsbrgg** [comment] 2018-11-19 16:53
Yes. The script I'm running is basically the same as it is on the `Samples` folder. From my logs, it's all being set perfectly, just the keyframes are not persisting.

**Comment by bbb999** [comment] 2018-11-19 16:55
If getKeys() returns an array of Time objects, in what way are the keyframes not persisting?

**Comment by dsbrgg** [comment] 2018-11-19 16:56
On the software itself, or am I wrong assuming these function should actually set the keyframes?

I supposed the `addKey` would literally add a keyframe on the software.

**Comment by bbb999** [comment] 2018-11-19 16:59
PPro must be adding the keyframes, otherwise you wouldn't get back an array of Time objects. 

Are you saying instead that PPro's UI doesn't update? 

Note that the sample snippet from which you're working, only updates the UI occasionally:

https://github.com/Adobe-CEP/Samples/blob/ed4d4656611780a0dafd98d16fac1d06ad27d8cb/PProPanel/jsx/PPRO/Premiere.jsx#L1347

If you like, you can update the UI after every change...

**Comment by dsbrgg** [comment] 2018-11-19 17:03
Sorry Bruce, that's exactly what I meant (the UI).
Yeah, I've got that part and basically the modification I made was on every second of the clip (180 seconds), I've added a keyframe with "random" value and updated on every second and like I've mentioned, in the end of the script I do see the last result but, the keyframes on the UI are not there, and scrolling through the clip show that only the last result from the script remained (not the keyframe though, only the actual value for the clip property).

**Comment by bbb999** [comment] 2018-11-19 17:08
That's...odd.

Send me your script, the ("Before") test project you're using, and step-by-step instructions on how we can reproduce the behavior you're seeing; b b b at adobe dot com.

**Comment by dsbrgg** [comment] 2018-11-19 17:12
Ok @bbb999! Will do as soon as I get to my computer. Thanks for the help!

**Comment by eliportell** [comment] 2018-11-19 17:55
I have noticed this as well. I will set keyframes, those keyframes will return properly when I ask to getKeys(), but the UI will not update (even though I told it to), and the animation will not be applied to the effect. 
[Same issue discussed here](https://forums.adobe.com/message/10534966#10534966)
It is inconsistent to reproduce for me. Sometimes the keyframes show up, other times they do not.

**Comment by bbb999** [comment] 2018-11-19 17:57
In your case, can you successfully access the array of Time values, which constitute the keyframe stream?

**Comment by eliportell** [comment] 2018-11-19 18:04
Yes. I addKey(), then setValueAtKey() with it forcing the UI to update, and then run getKeys(), and everything returns properly, but the UI does not update in the effects controls panel. 

Sound like the same issue exactly that @dsbrgg is having.

**Comment by bbb999** [comment] 2018-11-19 18:05
Great! 
I look forward to someone providing a script, test project, and steps we can follow to repro the behavior.

**Comment by dsbrgg** [comment] 2018-11-20 22:13
Hey @bbb999! I've sent an email with the script that I'm using. I think the test project might be "useless" because as I said, I'm just trying to play around with ExtendScript so, I literally just had an image on a video track and was trying to set `Scale` keyframes on each second (3 minutes - 180 seconds) that I left on the clip. 

Again, the script seems to run but, keyframes do not persist on the UI, just the last value that was set on the for loop (don't think this is a closure problem as the UI itself is not setting the last keyframe either).

**Comment by bbb999** [comment] 2018-11-20 23:14
Extensions.7z contains 5 Adobe extensions, and one third party: "com.my.test".

The only ExtendScript (.jsx) file in  com.my.test refers to your D:\WALLPAPERS directory, and doesn't seem keyframe-related. ;)

More likely locations: 

C:\Program Files (x86)\Common Files\Adobe\CEP\extensions
C:\Program Files\Common Files\Adobe\CEP\extensions

**Comment by dsbrgg** [comment] 2018-11-21 09:05
The file I've sent it `updateKeyframes.7z` which only contains the `updateKeyframes.jsx` file there. I think this is another thing.

**Comment by dsbrgg** [comment] 2018-11-21 13:42
Done!

**Comment by bbb999** [comment] 2018-11-21 14:04
I think the problem is this line: 

var updateUI = (q % 10 === 0); 

That will only ever be true when q is 0; otherwise, it'll be false. To see, try this in ESTK, with the JavaScript Console window open (to see the output):

for (var a = 0; a < 10; a++){
    var updateUI = (a % 10 === 0);
    $.writeln(updateUI);
}

**Comment by dsbrgg** [comment] 2018-11-22 06:43
Ok, I've modified it. Basically updating the UI in every iteration (180 then). Again, the UI updates but the keyframes are not saved there and not dislayed.

![premiere](https://user-images.githubusercontent.com/25888358/48885911-de8e4f80-ee21-11e8-8ed6-ba2c8a1ff750.PNG)

You think there could be anything else to try?

**Comment by dsbrgg** [comment] 2018-11-26 10:23
Hey @bbb999 ! Were you able to take a deeper look into this possible issue?

**Comment by bbb999** [comment] 2018-11-26 14:03
No; please send me your modified script, that updates the UI but for which the keyframes are not saved or displayed.

**Comment by dsbrgg** [comment] 2018-11-29 10:45
@bbb999 I've sent you the update script again yesterday, let me know if you had a chance to take a look at it.

**Comment by bbb999** [comment] 2018-11-29 19:50
I'm not seeing the behavior you're seeing; your script successfully adds a bunch of keyframes, and they persist across closing/re-opening the project.

https://www.dropbox.com/s/3ln4l4l0svj08jb/no_repro.mp4

**Comment by dsbrgg** [comment] 2018-11-29 20:59
Guess I'll try reinstalling Premiere. Thanks a lot for the help Bruce!

**Comment by bbb999** [comment] 2018-11-29 21:00
Confirming: In the video, it looks like I'm doing the same thing you are, right?

**Comment by dsbrgg** [comment] 2018-11-29 21:33
Yes, I mean, it does look like the same thing. The only difference is the Premiere version but I assume the API wouldn't change or else, I would not even be able to link on the ExtendScript Tool.

**Comment by bbb999** [comment] 2018-11-29 21:34
In what version are you seeing the problem? I can test there too...

**Comment by bbb999** [comment] 2018-12-31 21:51
Can we close this one?

**Closed** 2019-12-03 14:51 UTC
